var HeaderConfig = {
    menulist:[
      {
        key:'top',
        url:`/`,
        icon:'to-top',
        title:'头条'
      },
      {
        key:'guonei',
        url:`/guonei`,
        icon:'minus-square',
        title:'国内'
      },
      {
        key:'guoji',
        url:`/guoji`,
        icon:'global',
        title:'国际'
      },
      {
        key:'tiyu',
        url:`/tiyu`,
        icon:'smile',
        title:'体育'
      },
      {
        key:'yule',
        url:`/yule`,
        icon:'appstore',
        title:'娱乐'
      },
      {
        key:'junshi',
        url:`/junshi`,
        icon:'rocket',
        title:'军事'
      },
      {
        key:'keji',
        url:`/keji`,
        icon:'fork',
        title:'科技'
      },
      {
        key:'shishang',
        url:`/shishang`,
        icon:'dingding',
        title:'时尚'
      }
    ]
}
module.exports =  HeaderConfig;